"""Report generation in multiple formats"""

import json
from typing import Dict, List
from datetime import datetime


class ReportGenerator:
    """Generates analysis reports in various formats"""
    
    def generate_markdown(self, analysis: Dict, output_path: str):
        """Generate markdown report"""
        md = self._build_markdown(analysis)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md)
    
    def generate_json(self, analysis: Dict, output_path: str):
        """Generate JSON report"""
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(analysis, f, indent=2, ensure_ascii=False)
    
    def generate_comparison(self, analyses: List[Dict], output_path: str):
        """Generate comparison report for multiple repositories"""
        md = "# Repository Comparison Report\n\n"
        md += f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        md += "---\n\n"
        
        # Summary table
        md += "## Quick Comparison\n\n"
        md += "| Repository | Stars | Health | Security | Activity |\n"
        md += "|------------|-------|--------|----------|----------|\n"
        
        for analysis in analyses:
            md += f"| {analysis['repo_name']} | "
            md += f"{analysis['stars']:,} | "
            md += f"{analysis['health_score']}/100 | "
            md += f"{analysis['security_score']}/100 | "
            md += f"{analysis['activity']['level']} |\n"
        
        md += "\n---\n\n"
        
        # Detailed sections for each repo
        for analysis in analyses:
            md += f"## {analysis['repo_name']}\n\n"
            md += self._build_summary_section(analysis)
            md += "\n---\n\n"
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(md)
    
    def _build_markdown(self, analysis: Dict) -> str:
        """Build complete markdown report"""
        md = f"# Repository Analysis: {analysis['repo_name']}\n\n"
        md += f"*Generated: {datetime.fromisoformat(analysis['analyzed_at']).strftime('%Y-%m-%d %H:%M:%S UTC')}*\n\n"
        md += "---\n\n"
        
        # Executive Summary
        md += "## 📊 Executive Summary\n\n"
        md += self._build_summary_section(analysis)
        
        # Detailed Metrics
        md += "## 📈 Detailed Metrics\n\n"
        md += self._build_metrics_section(analysis)
        
        # Language Analysis
        md += "## 💻 Language Distribution\n\n"
        md += self._build_language_section(analysis)
        
        # Activity Analysis
        md += "## 🔥 Activity Analysis\n\n"
        md += self._build_activity_section(analysis)
        
        # Community Health
        md += "## 👥 Community Health\n\n"
        md += self._build_community_section(analysis)
        
        # Security Assessment
        md += "## 🔒 Security Assessment\n\n"
        md += self._build_security_section(analysis)
        
        # AI Insights
        md += "## 🧠 AI-Powered Insights\n\n"
        md += self._build_insights_section(analysis)
        
        # Footer
        md += "\n---\n\n"
        md += "*Report generated by [AI-Powered GitHub Repo Analyzer](https://github.com/1Rachel02/github-repo-analyzer)*\n"
        
        return md
    
    def _build_summary_section(self, analysis: Dict) -> str:
        """Build executive summary section"""
        md = f"**Overall Health Score:** {analysis['health_score']}/100 "
        md += self._get_score_emoji(analysis['health_score']) + "\n\n"
        
        md += "### Key Metrics\n\n"
        md += f"- ⭐ **Stars:** {analysis['stars']:,}\n"
        md += f"- 🍴 **Forks:** {analysis['forks']:,}\n"
        md += f"- 👀 **Watchers:** {analysis['watchers']:,}\n"
        md += f"- 💻 **Primary Language:** {analysis['language']}\n"
        md += f"- 🔒 **Security Score:** {analysis['security_score']}/100\n"
        md += f"- 🔥 **Activity Level:** {analysis['activity']['level']}\n\n"
        
        return md
    
    def _build_metrics_section(self, analysis: Dict) -> str:
        """Build detailed metrics section"""
        basic = analysis['basic_metrics']
        
        md = f"- **Repository Size:** {basic['size_kb']:,} KB\n"
        md += f"- **Open Issues:** {basic['open_issues']}\n"
        md += f"- **Default Branch:** `{basic['default_branch']}`\n"
        md += f"- **Created:** {basic['created_at'][:10]}\n"
        md += f"- **Last Updated:** {basic['updated_at'][:10]}\n"
        md += f"- **Last Push:** {basic['pushed_at'][:10]}\n"
        
        features = []
        if basic['has_wiki']: features.append("Wiki")
        if basic['has_pages']: features.append("GitHub Pages")
        if basic['has_downloads']: features.append("Downloads")
        
        if features:
            md += f"- **Features:** {', '.join(features)}\n"
        
        if basic['is_fork']:
            md += "- ⚠️ *This is a forked repository*\n"
        if basic['is_archived']:
            md += "- ⚠️ *This repository is archived*\n"
        
        md += "\n"
        return md
    
    def _build_language_section(self, analysis: Dict) -> str:
        """Build language analysis section"""
        langs = analysis['languages']
        
        md = f"**Primary Language:** {langs['primary']}\n\n"
        md += f"**Diversity Score:** {langs['diversity_score']}/100\n\n"
        
        if langs['distribution']:
            md += "### Distribution\n\n"
            for lang, pct in sorted(langs['distribution'].items(), key=lambda x: x[1], reverse=True):
                bar = "█" * int(pct / 5)
                md += f"- **{lang}:** {pct}% {bar}\n"
            md += "\n"
        
        return md
    
    def _build_activity_section(self, analysis: Dict) -> str:
        """Build activity analysis section"""
        activity = analysis['activity']
        
        md = f"**Activity Level:** {activity['level']} ({activity['score']}/100)\n\n"
        md += f"- **Days Since Last Push:** {activity['days_since_last_push']}\n"
        md += f"- **Recent Commits Analyzed:** {activity['recent_commits']}\n\n"
        
        return md
    
    def _build_community_section(self, analysis: Dict) -> str:
        """Build community health section"""
        community = analysis['community']
        
        md = f"**Community Score:** {community['score']}/100 "
        md += self._get_score_emoji(community['score']) + "\n\n"
        
        md += "### Documentation & Governance\n\n"
        md += f"- {'✅' if community['has_readme'] else '❌'} README\n"
        md += f"- {'✅' if community['has_license'] else '❌'} License\n"
        md += f"- {'✅' if community['has_contributing'] else '❌'} Contributing Guidelines\n"
        md += f"- {'✅' if community['has_code_of_conduct'] else '❌'} Code of Conduct\n\n"
        
        md += "### Engagement\n\n"
        md += f"- **Contributors:** {community['contributors_count']}\n"
        md += f"- **Open Issues:** {community['open_issues_count']}\n\n"
        
        return md
    
    def _build_security_section(self, analysis: Dict) -> str:
        """Build security assessment section"""
        security = analysis['security']
        
        md = f"**Security Score:** {security['score']}/100 "
        md += self._get_score_emoji(security['score']) + "\n\n"
        
        md += f"- {'✅' if security['has_security_policy'] else '❌'} Security Policy (SECURITY.md)\n\n"
        
        if security['issues']:
            md += "### Security Issues Detected\n\n"
            for issue in security['issues']:
                md += f"- ⚠️ {issue}\n"
            md += "\n"
        else:
            md += "✅ No major security issues detected\n\n"
        
        return md
    
    def _build_insights_section(self, analysis: Dict) -> str:
        """Build AI insights section"""
        insights = analysis['insights']
        
        md = "### 💪 Strengths\n\n"
        for strength in insights['strengths']:
            md += f"- ✅ {strength}\n"
        md += "\n"
        
        md += "### ⚠️ Areas for Improvement\n\n"
        for weakness in insights['weaknesses']:
            md += f"- 🔸 {weakness}\n"
        md += "\n"
        
        md += "### 💡 Recommendations\n\n"
        for i, rec in enumerate(insights['recommendations'], 1):
            md += f"{i}. {rec}\n"
        md += "\n"
        
        return md
    
    def _get_score_emoji(self, score: int) -> str:
        """Get emoji based on score"""
        if score >= 80:
            return "🟢"
        elif score >= 60:
            return "🟡"
        elif score >= 40:
            return "🟠"
        else:
            return "🔴"
